### ISSUE TITLE
obsolete?

### ISSUE THREAD

**Issue by adjenks** [tobyhede/postsql#2]
Is this library obsolete now due new postgresql json functions and operators?

```
SELECT id, json_string(data,'name') FROM things
WHERE json_string(data,'name') LIKE 'G%';
```
compared to:
```
SELECT id, data#>'{"name"}' FROM things
WHERE data#>'{"name"}' LIKE 'G%';
```
It looks like those operators came out in version 9.3, September 9, 2013. Which... looks like the month after you stopped commiting changes to this library.

**Comment by tobyhede** [comment]
Heya @adjenks ... yes, pretty much. This was all a work around before those features dropped.
